export interface OperaconFinanciera {
    tipo: String,
    color: String,
    programacion: String,
    estado: String,
    numero_ciclo: number,
    fecha_inicio: String,
    fecha_fin: String,
    monto_gasto: number,
    monto_ahorro_inicial: number,
    monto_capital: number,
    tasa_aporte_inicial: number,
    tasa_aporte_capital: number,
    tasa_aporte_programado: number,
    tasa_interes: number,
    tasa_mora: number,
    se_desembolso_prestamo: boolean,
    comentario: String,
    persona: String,
    detalle: Object[]
}